### ISSUE TITLE
Request: Support for ADB wireless

### ISSUE THREAD

**Issue by mmarquezs** [spion/adbfs-rootless#17]
It would be nice to support adb over wifi

**Comment by Aire-One** [comment]
It is an android native feature, you just need a rooted device and to type the following command as root :
`setprop service.adb.tcp.port <port>`
Where port is the listening port (default port to use is 5555).

Then on our computer use :
`adb connect <device-ip> [port]`
port parameter is optional, by default it will try on port 5555.

You can then mount your device through ADBFS to make it works over wifi.

**Comment by mmarquezs** [comment]
I already know about that. With "ADB wireless" I meant that native feature.

I opened this bug some time ago, but I remember when I test it it didn't work when adb was connected on wireless. It might work now I haven't test it in a long time.

**Comment by mmarquezs** [comment]
I just test it it seems to work fine now so... I don't know what was causing issues nevermind I will close this issue unless I find any other issue.
