### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Xerus2000** [spion/adbfs-rootless#29]
```
make: pkg-config: Command not found
g++ -c -o adbfs.o adbfs.cpp  
In file included from /usr/include/fuse/fuse.h:26:0,
                 from /usr/include/fuse.h:9,
                 from utils.h:37,
                 from adbfs.cpp:75:
/usr/include/fuse/fuse_common.h:33:2: error: #error Please add -D_FILE_OFFSET_BITS=64 to your compile flags!
 #error Please add -D_FILE_OFFSET_BITS=64 to your compile flags!
  ^~~~~
Makefile:12: recipe for target 'adbfs.o' failed
make: *** [adbfs.o] Error 1
```

After cloning the repo and calling make, the error above appears. What am I doing wrong?

I am on Kubuntu 18.04

**Comment by Xerus2000** [comment]
Simply installing `pkg-config` seems to have fixed it.

**Comment by alexanderadam** [comment]
> Simply installing `pkg-config` seems to have fixed it.

Hm, sadly this doesn't seem to work for me. I have `pkg-config` installed but it still doesn't work:

![❯ sudo apt install pkg-config Reading package lists... Done Building dependency tree        Reading state information... Done pkg-config is already the newest version (0.29.1-0ubuntu4). The following packages were automatically installed and are no longer required:   libykpers-1-1 libyubikey-udev libyubikey0 libzxcvbn0 Use 'sudo apt autoremove' to remove them. 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.  adbfs-rootless on  master on ☁️   ❯ make Package fuse was not found in the pkg-config search path. Perhaps you should add the directory containing `fuse.pc' to the PKG_CONFIG_PATH environment variable No package 'fuse' found g++ -c -o adbfs.o adbfs.cpp -Wall   In file included from /usr/include/fuse/fuse.h:26:0,                  from /usr/include/fuse.h:9,                  from utils.h:37,                  from adbfs.cpp:75: /usr/include/fuse/fuse_common.h:33:2: error: #error Please add -D_FILE_OFFSET_BITS=64 to your compile flags!  #error Please add -D_FILE_OFFSET_BITS=64 to your compile flags!   ^ adbfs.cpp: In function 'int adb_readlink(const char*, char*, size_t)': adbfs.cpp:966:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]      for (num_slashes = ii = 0; ii < strlen(path); ii++)                                    ^ make: *** [Makefile:14: adbfs.o] Error 1](https://user-images.githubusercontent.com/372620/102759869-00e25680-4375-11eb-8544-76646e81ac68.png)
